name: Manifest_update
on:
  - pull_request_target

permissions:
  actions: write
  contents: write
  pull-requests: write
  repository-projects: write

jobs:
  manifest_update:
    runs-on: ubuntu-latest
    steps:
     - uses: rugeGerritsen/action-manifest-update@main
       with:
         github-token: '${{ secrets.GITHUB_TOKEN }}'
         module-path: '${{ github.repository }}'
         manifest-repo-path: 'rugeGerritsen/sdk-nrf'
         manifest-file: 'west.yml'
         module-pull-nr: '${{ github.event.number }}'
