name: Manifest_update
on:
  pull_request:
    types:
      - opened
      - edited

jobs:
  manifest_update:
    runs-on: ubuntu-latest
    name: manifest_update
    steps:
      - name: Printer
        run: python3 -c "print('Hello world')"